// @match        https://app.stormgain.com/crypto-miner/
// @match        https://app.freecardano.com/*
// @match        https://app.freebinancecoin.com/*
// @match        https://app.freebitcoin.io/*
// @match        https://app.freedash.io/*
// @match        https://app.free-doge.com/*
// @match        https://app.freeethereum.com/*
// @match        https://app.freecryptom.com/*
// @match        https://app.free-ltc.com/*
// @match        https://app.freeneo.io/*
// @match        https://app.freesteam.io/*
// @match        https://app.free-tron.com/*
// @match        https://app.freeusdcoin.com/*
// @match        https://app.freetether.com/*
// @match        https://app.freenem.com/*
// @match        https://app.freeshibainu.com/*
// @match        https://app.coinfaucet.io/*
// @match        https://app.freepancake.com/*
// @match        https://app.freematic.com/*
// @match        https://app.freebittorrent.com/*
// @match        https://app.freebfg.com/*
// @match        https://freebitco.in/*
// @match        https://faucetpay.io/*
// @match        https://bigbtc.win/*
// @match        https://www.bestchange.com/*
// @match        https://faucetok.net/*
// @match        https://betfury.io/boxes/all*
// @match        https://www.free-doge.io/
// @match        https://www.free-doge.io/free/
// @match        https://autofaucet.dutchycorp.space/login.php*
// @match        https://autofaucet.dutchycorp.space/roll.php*
// @match        https://autofaucet.dutchycorp.space/coin_roll.php*
// @match        https://express.dutchycorp.space/index.php*
// @match        https://express.dutchycorp.space/roll.php*
// @match        https://express.dutchycorp.space/coin_roll.php*
// @match        https://faucetcrypto.com/dashboard
// @match        https://faucetcrypto.com/task/faucet-claim
// @match        https://faucetcrypto.com/ptc/*
// @match        https://faucetcrypto.com/task/ptc-advertisement/*
// @match        https://faupig-bit.online/page/dashboard*
// @match        https://faupig-bit.online/account/login/not-logged-in
// @match        https://freegridco.in/*
// @match        https://james-trussy.com/*
// @match        https://www.only1024.com/f*
// @match        https://criptologico.com/tools/cc*
// @match        https://yescoiner.com/*
// @match        https://coindiversity.io/*
// @match        https://ltcfaucet.top/*
// @match        https://bnbfaucet.top/*
// @match        https://dogecoinfaucet.top/*
// @match        https://tronfaucet.top/*
// @match        https://ethfaucet.top/*
// @match        https://freebch.club/*
// @match        https://zecfaucet.net/*
// @match        https://faucet.monster/*
// @match        https://auto-crypto.ml/*
// @match        https://claimclicks.com/*
// @match        https://cryptoclicks.net/*
// @match        https://freeshiba.cf/*
// @match        https://auto-crypto.click/*
