// @match        https://app.stormgain.com/crypto-miner/
// @match        https://freecardano.com/*
// @match        https://freebinancecoin.com/*
// @match        https://freebitcoin.io/*
// @match        https://freedash.io/*
// @match        https://free-doge.com/*
// @match        https://freeethereum.com/*
// @match        https://freecryptom.com/*
// @match        https://free-ltc.com/*
// @match        https://freeneo.io/*
// @match        https://freesteam.io/*
// @match        https://free-tron.com/*
// @match        https://freeusdcoin.com/*
// @match        https://freetether.com/*
// @match        https://freenem.com/*
// @match        https://freeshibainu.com/*
// @match        https://coinfaucet.io/*
// @match        https://freebitco.in/*
// @match        https://faucetpay.io/*
// @match        https://bigbtc.win/*
// @match        https://www.bestchange.com/*
// @match        https://faucetok.net/*
// @match        https://betfury.io/boxes/all*
// @match        https://www.free-doge.io/
// @match        https://www.free-doge.io/free/
// @match        https://autofaucet.dutchycorp.space/login.php*
// @match        https://autofaucet.dutchycorp.space/roll.php*
// @match        https://autofaucet.dutchycorp.space/coin_roll.php*
// @match        https://express.dutchycorp.space/index.php*
// @match        https://express.dutchycorp.space/roll.php*
// @match        https://express.dutchycorp.space/coin_roll.php*
// @match        https://faucetcrypto.com/dashboard
// @match        https://faucetcrypto.com/task/faucet-claim
// @match        https://faucetcrypto.com/ptc/*
// @match        https://faucetcrypto.com/task/ptc-advertisement/*
// @match        https://faupig-bit.online/page/dashboard*
// @match        https://faupig-bit.online/account/login/not-logged-in
// @match        https://freepancake.com/*
// @match        https://freegridco.in/*
// @match        https://freematic.com/*
// @match        https://freebch.fun/page/dashboard*
// @match        https://freebch.fun/account/login/not-logged-in
// @match        https://james-trussy.com/*
// @match        https://www.only1024.com/f*
// @match        https://criptologico.com/tools/cc*
// @match        https://freebittorrent.com/*
// @match        https://freebfg.com/*
// @match        https://yescoiner.com/*
// @match        https://coindiversity.io/*
// @match        https://bscads.com/*
// @match        https://ltcfaucet.top/*
// @match        https://bnbfaucet.top/*
// @match        https://dogecoinfaucet.top/*
// @match        https://tronfaucet.top/*
// @match        https://ethfaucet.top/*
// @match        https://freebch.club/*
// @match        https://zecfaucet.net/*
// @match        https://faucet.monster/*
// @match        https://auto-crypto.ml/*
// @match        https://claimclicks.com/*
// @match        https://cryptoclicks.net/*
// @match        https://freeshiba.cf/*
// @match        https://auto-crypto.click/*
